image: docker:stable

services:
  - docker:dind

variables:
  IMAGE_DISCOVERY: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build-discovery:
  stage: build
  script:
    - docker pull $IMAGE_DISCOVERY:latest || true
    - docker build --cache-from $IMAGE_DISCOVERY:latest --tag $IMAGE_DISCOVERY:$CI_COMMIT_REF_NAME --tag $IMAGE_DISCOVERY:latest .
    - docker push $IMAGE_DISCOVERY:$CI_COMMIT_REF_NAME
    - docker push $IMAGE_DISCOVERY:latest

build-discovery-tag:
  stage: build
  script:
    - docker pull $IMAGE_DISCOVERY:latest || true
    - docker build --cache-from $IMAGE_DISCOVERY:latest --tag $IMAGE_DISCOVERY:$CI_COMMIT_TAG  .
    - docker push $IMAGE_DISCOVERY:$CI_COMMIT_REF_NAME
  only:
    - tags
