image: docker:stable

services:
  - docker:dind

variables:
  IMAGE_SCHEDULER: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build-scheduler:
  stage: build
  script:
    - docker pull $IMAGE_SCHEDULER:latest || true
    - docker build --cache-from $IMAGE_SCHEDULER:latest --tag $IMAGE_SCHEDULER:$CI_COMMIT_REF_NAME --tag $IMAGE_SCHEDULER:latest .
    - docker push $IMAGE_SCHEDULER:$CI_COMMIT_REF_NAME
    - docker push $IMAGE_SCHEDULER:latest

build-scheduler-tag:
  stage: build
  script:
    - docker pull $IMAGE_SCHEDULER:latest || true
    - docker build --cache-from $IMAGE_SCHEDULER:latest --tag $IMAGE_SCHEDULER:$CI_COMMIT_TAG  .
    - docker push $IMAGE_SCHEDULER:$CI_COMMIT_REF_NAME
  only:
    - tags
